Replaced `invokeMethod` with `invokeMethodAsync`
IEvangelist/blazorators pull request #35
Opened 2022-10-07 18:51 UTC by MahmudX

Using `invokeMethod` throws the following error -
```
Uncaught Error: The current dispatcher does not support synchronous calls from JS to .NET. Use invokeMethodAsync instead.
    at y (blazor.server.js:1:1840)
    at C.invokeMethod (blazor.server.js:1:3960)
    at onSuccess (geolocation.js:19:15)
    at geolocation.js:41:25
```

This issue can be overcome by using the async method.

2022-10-07 18:55 UTC, IEvangelist requested changes
This looks good, thank you. We'll :shipit: when you make the suggested changes. Let's revert the changed indentation style changes on the methods that were otherwise untouched.

2022-10-07 18:57 UTC, IEvangelist commented
Hey @all-contributors, please add @MahmudX for code

2022-10-07 19:17 UTC, IEvangelist commented
@all-contributors please add @MahmudX for code

2022-10-07 20:44 UTC, MahmudX commented
All the indentations were unintentional. Copy paste, I guess! 😛

2022-10-07 20:47 UTC, MahmudX reviewed
I think now the indentations are good

2022-10-10 14:14 UTC, IEvangelist approved these changes

2022-10-10 14:14 UTC, merged